[project]
name = "Surftopo"
version = "0.1.0"
description = "Surftopo library"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch==2.5.1",
    "numpy==2.1.3",
    "scikit-image==0.24.0"
]